version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./fontconfig_cache:/fontconfig_cache
    environment:
      # Tells matplotlib where it can write the config file
      - MPLCONFIGDIR=/tmp/matplotlib
      # Tells fontconfig where it can write its cache
      - FONTCONFIG_PATH=/fontconfig_cache
      - SECRET_KEY=devsecretkey
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DJANGO_SETTINGS_MODULE=app.settings.dev
      - ALLOWED_HOSTS=*
    depends_on:
      - db

  db:
    image: postgres:14.9
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
