#!/usr/bin/env bash
# Install skills, agents, cited rules, the connector/plugin catalog, and the shared
# pre-commit gate lib from a private dotagents checkout into Cursor Cloud Agent home paths.
# Skills → ~/.cursor/skills; agents → ~/.cursor/agents;
# cited rules → ~/.cursor/dotagents-package/rules;
# mcps/catalog.json → ~/.cursor/dotagents-package/mcps (so /optimize-workspaces can reconcile live
# connectors/plugins against the canon on a VM with no laptop checkout);
# gate/gate-lib.sh → ~/.cursor/dotagents-package/gate/gate-lib.sh plus a stub symlink at
# ~/code/dotagents/gate/gate-lib.sh, the default path child-repo pre-commit shims source
# (`${DOTAGENTS_GATE_LIB:-$HOME/code/dotagents/gate/gate-lib.sh}`), so no env export or
# shell-profile edit is needed. The stub is not a full checkout.
# Idempotent: safe to re-run from environment.json install/update.
#
# Source (first match):
#   1. $DOTAGENTS_ROOT if it looks like this repo
#   2. The checkout that contains this script (templates/cloud-agent/), if it looks like this repo
#   3. $HOME/code/dotagents if it looks like this repo (skills+agents+rules; a
#      gate-lib stub alone does not count)
#   4. Fetch this private repo ($DOTAGENTS_CLONE_URL, default
#      https://github.com/jsolly/dotagents.git), preferring credentials gh already
#      has, then falling back to git clone:
#        a. gh api tarball
#        b. gh repo clone (shallow, sparse)
#        c. git clone --depth 1 --sparse
# Never clones a public skills mirror. Does not vendor the full private tree
# into the child repo working tree — copies only into VM home paths.
# Every input (skills, agents, rules, skills/laptop-only.txt, mcps/catalog.json,
# gate/gate-lib.sh) is required; a checkout missing one fails before anything is installed.
# agents/ and rules/ .retired-md-blobs are optional: without them the pre-manifest seed prune is
# skipped with a warning.
# Laptop-only skills stay off cloud VMs (skills/laptop-only.txt).
# Re-runs prune dest skill dirs that are retired or now laptop-only, and agent/rule *.md
# files a previous run installed (per the dest dir's own .dotagents-installed manifest) that
# left the source, so a leftover copied playbook (for example a deleted skills/integration-verify)
# or a manifest-listed retired agent/rule cannot stay loadable. Copies from installers older than the manifest are
# pruned only when byte-identical to a historical dotagents version of that retired path (the
# committed .retired-md-blobs list). A retired-name file that differs (user-edited or a symlink)
# stays loadable and is warned about on every run; any other agent/rule file is left alone.
set -euo pipefail

PACKAGE_HOME="${HOME}/.cursor/dotagents-package"
SKILLS_HOME="${CURSOR_CLOUD_SKILLS_HOME:-${HOME}/.cursor/skills}"
AGENTS_HOME="${CURSOR_CLOUD_AGENTS_HOME:-${HOME}/.cursor/agents}"
RULES_HOME="${CURSOR_CLOUD_PACKAGE_RULES:-${PACKAGE_HOME}/rules}"
MCPS_HOME="${CURSOR_CLOUD_PACKAGE_MCPS:-${PACKAGE_HOME}/mcps}"
GATE_HOME="${CURSOR_CLOUD_PACKAGE_GATE:-${PACKAGE_HOME}/gate}"
GATE_LIB_PATH="${GATE_HOME}/gate-lib.sh"
# Each agent/rule dest dir keeps its own install manifest, so overridden dests never share one.
INSTALL_MANIFEST_NAME=".dotagents-installed"
# Per source kind dir: "<git blob> <name>.md" for every version a retired name ever held
# (generated by scripts/retired-md-blobs.sh). Seeds pruning for pre-manifest copies.
RETIRED_BLOBS_NAME=".retired-md-blobs"
# Sparse fetch set. skills+agents+rules are required for looks_like_dotagents;
# mcps carries the connector catalog; gate carries gate-lib.sh for child pre-commits.
CLOUD_SPARSE_DIRS=(skills agents rules mcps gate)

looks_like_dotagents() {
  local root="$1"
  [[ -n "$root" && -d "$root/skills" && -d "$root/agents" && -d "$root/rules" ]] || return 1
  local f
  shopt -s nullglob
  for f in "$root/skills"/*/SKILL.md; do
    shopt -u nullglob
    [[ -f "$f" ]] && return 0
  done
  shopt -u nullglob
  return 1
}

append_skip_names() {
  local file="$1"
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    LAPTOP_ONLY+=("$line")
  done < "$file"
}

read_laptop_only() {
  local root="$1"
  LAPTOP_ONLY=()
  append_skip_names "$root/skills/laptop-only.txt"
}

is_laptop_only() {
  local name="$1" x
  for x in "${LAPTOP_ONLY[@]+"${LAPTOP_ONLY[@]}"}"; do
    [[ "$x" == "$name" ]] && return 0
  done
  return 1
}

clone_tmp=""
cleanup() {
  if [[ -n "$clone_tmp" ]]; then
    rm -rf "$clone_tmp"
  fi
}
trap cleanup EXIT

resolve_root() {
  local script_dir repo
  if looks_like_dotagents "${DOTAGENTS_ROOT:-}"; then
    printf '%s\n' "$(cd "$DOTAGENTS_ROOT" && pwd)"
    return 0
  fi
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # templates/cloud-agent/install-cloud-skills.sh → repo root
  repo="$(cd "$script_dir/../.." && pwd)"
  if looks_like_dotagents "$repo"; then
    printf '%s\n' "$repo"
    return 0
  fi
  if looks_like_dotagents "${HOME}/code/dotagents"; then
    printf '%s\n' "$(cd "${HOME}/code/dotagents" && pwd)"
    return 0
  fi
  return 1
}

# Drop userinfo so https://token@github.com/org/repo still maps to org/repo
# and never appears in installer logs.
strip_url_userinfo() {
  local url="$1" scheme after
  if [[ "$url" == *://*@* ]]; then
    scheme="${url%%://*}"
    after="${url#*://}"
    after="${after#*@}"
    printf '%s://%s\n' "$scheme" "$after"
    return 0
  fi
  printf '%s\n' "$url"
}

# Map a git remote URL to GitHub owner/repo. Non-github URLs (file:// fixtures) fail.
github_nwo_from_url() {
  local url="$1" rest owner repo
  url="$(strip_url_userinfo "$url")"
  url="${url%%#*}"
  url="${url%%\?*}"
  url="${url%/}"
  url="${url%.git}"
  case "$url" in
    https://github.com/* | http://github.com/*)
      rest="${url#*github.com/}"
      ;;
    git@github.com:*)
      rest="${url#git@github.com:}"
      ;;
    ssh://git@github.com/*)
      rest="${url#ssh://git@github.com/}"
      ;;
    github.com/*)
      rest="${url#github.com/}"
      ;;
    *)
      return 1
      ;;
  esac
  rest="${rest#/}"
  owner="${rest%%/*}"
  rest="${rest#"$owner"}"
  rest="${rest#/}"
  repo="${rest%%/*}"
  [[ -n "$owner" && -n "$repo" && "$owner" != *"/"* ]] || return 1
  printf '%s/%s\n' "$owner" "$repo"
}

sparse_checkout() {
  local dest="$1"
  git -C "$dest" sparse-checkout set "${CLOUD_SPARSE_DIRS[@]}"
}

# GitHub tarballs unpack to a single {owner}-{repo}-{sha}/ prefix. Extract only
# the sparse dirs so ONE-FILE-DOCUMENT.md and other laptop files stay out.
unpack_github_tarball() {
  local tarball="$1" dest="$2"
  local prefix d
  prefix=""
  while IFS= read -r d; do
    prefix="${d%%/*}"
    break
  done < <(tar -tzf "$tarball")
  [[ -n "$prefix" ]] || return 1
  mkdir -p "$dest"
  tar -xzf "$tarball" -C "$dest" --strip-components=1 "${CLOUD_SPARSE_DIRS[@]/#/${prefix}/}" || return 1
  looks_like_dotagents "$dest"
}

fetch_via_gh_tarball() {
  local nwo="$1" ref="$2" dest="$3"
  local tarball
  command -v gh >/dev/null 2>&1 || return 1
  echo "cloud-package: fetching ${nwo}@${ref} via gh api tarball"
  rm -rf "$dest"
  mkdir -p "$dest"
  tarball="$(mktemp "${clone_tmp}/tarball.XXXXXX")"
  if ! GH_PAGER=cat gh api "repos/${nwo}/tarball/${ref}" >"$tarball"; then
    echo "cloud-package: gh api tarball failed for ${nwo}@${ref}"
    return 1
  fi
  if [[ ! -s "$tarball" ]]; then
    echo "cloud-package: gh api tarball returned an empty body"
    return 1
  fi
  unpack_github_tarball "$tarball" "$dest"
}

fetch_via_gh_repo_clone() {
  local nwo="$1" ref="$2" dest="$3"
  command -v gh >/dev/null 2>&1 || return 1
  echo "cloud-package: cloning ${nwo}@${ref} via gh repo clone (shallow, sparse)"
  rm -rf "$dest"
  GH_PAGER=cat gh repo clone "$nwo" "$dest" -- --depth 1 --filter=blob:none --sparse --branch "$ref" || return 1
  sparse_checkout "$dest"
  looks_like_dotagents "$dest"
}

fetch_via_git_clone() {
  local url="$1" ref="$2" dest="$3"
  echo "cloud-package: cloning $(strip_url_userinfo "$url")@${ref} via git clone (shallow, sparse)"
  rm -rf "$dest"
  GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=true git clone --depth 1 --filter=blob:none --sparse --branch "$ref" \
    "$url" "$dest" || return 1
  sparse_checkout "$dest"
  looks_like_dotagents "$dest"
}

fetch_failed() {
  local url="$1" ref="$2"
  echo "cloud-package: ERROR — could not fetch private dotagents ($(strip_url_userinfo "$url")@${ref})." >&2
  echo "cloud-package: Set DOTAGENTS_ROOT to a checkout of jsolly/dotagents, or grant this environment git/gh access to that repo (GitHub App allowlist + environment.json repositoryDependencies: github.com/jsolly/dotagents). GitHub MCP read access is not git clone credentials. Do not vendor the private tree into this working copy." >&2
  exit 1
}

install_gate_lib() {
  local src="$1/gate/gate-lib.sh"
  local stub="${HOME}/code/dotagents/gate/gate-lib.sh"
  mkdir -p "$GATE_HOME"
  cp -f "$src" "$GATE_LIB_PATH"
  # Child shims default to $HOME/code/dotagents/gate/gate-lib.sh, which works in every
  # shell (including non-login `bash -c` git hooks). A real ~/code/dotagents checkout
  # already provides it (and resolve_root installs from that checkout); never replace it.
  if ! looks_like_dotagents "${HOME}/code/dotagents"; then
    mkdir -p "$(dirname "$stub")"
    ln -sfn "$GATE_LIB_PATH" "$stub"
  fi
  echo "cloud-package: installed gate lib → ${GATE_LIB_PATH}"
  return 0
}

root=""
if root="$(resolve_root)"; then
  echo "cloud-package: using local checkout $root"
else
  clone_url="${DOTAGENTS_CLONE_URL:-https://github.com/jsolly/dotagents.git}"
  clone_ref="${DOTAGENTS_CLONE_REF:-main}"
  clone_tmp="$(mktemp -d)"
  dest="$clone_tmp/dotagents"
  nwo=""
  fetched=0
  echo "cloud-package: no local checkout; fetching $(strip_url_userinfo "$clone_url")@${clone_ref} (authenticated gh, then git clone; sparse)"
  if nwo="$(github_nwo_from_url "$clone_url")"; then
    if fetch_via_gh_tarball "$nwo" "$clone_ref" "$dest"; then
      fetched=1
    elif fetch_via_gh_repo_clone "$nwo" "$clone_ref" "$dest"; then
      fetched=1
    fi
  fi
  if [[ "$fetched" -eq 0 ]]; then
    if fetch_via_git_clone "$clone_url" "$clone_ref" "$dest"; then
      fetched=1
    fi
  fi
  if [[ "$fetched" -eq 0 ]]; then
    fetch_failed "$clone_url" "$clone_ref"
  fi
  root="$dest"
  if ! looks_like_dotagents "$root"; then
    echo "cloud-package: ERROR — fetch at $root is not a dotagents checkout" >&2
    fetch_failed "$clone_url" "$clone_ref"
  fi
fi

# looks_like_dotagents already required skills/, agents/, and rules/ on every root path.
src_skills="$root/skills"
# Child pre-commits source the gate lib, /optimize-workspaces reconciles against the
# catalog, and an absent skip list would ship every laptop-only skill, so a checkout
# without any of them is not installable.
for required in skills/laptop-only.txt mcps/catalog.json gate/gate-lib.sh; do
  if [[ ! -f "$root/$required" ]]; then
    echo "cloud-package: ERROR — no ${required} in checkout $root" >&2
    exit 1
  fi
done

read_laptop_only "$root"

# Currently shipped = source SKILL.md and not laptop-only. Copy and prune
# both use this so a new skip reason cannot leave a leftover dest loadable.
should_ship_skill() {
  local name="$1"
  [[ -f "$src_skills/$name/SKILL.md" ]] || return 1
  if is_laptop_only "$name"; then
    return 1
  fi
  return 0
}

# --- skills (required) ---

mkdir -p "$SKILLS_HOME"
installed_skills=0
skipped_excluded=0
for skill_dir in "$src_skills"/*/; do
  [[ -d "$skill_dir" ]] || continue
  name="$(basename "$skill_dir")"
  if ! should_ship_skill "$name"; then
    if is_laptop_only "$name"; then
      echo "cloud-package: skip skill ${name} (laptop-only)"
      skipped_excluded=$((skipped_excluded + 1))
    else
      echo "cloud-package: skip skill ${name} (no SKILL.md)"
    fi
    continue
  fi
  dest="$SKILLS_HOME/$name"
  if [[ -L "$dest" ]]; then
    rm -f -- "$dest"
  else
    rm -rf -- "$dest"
  fi
  cp -R "$skill_dir" "$dest"
  installed_skills=$((installed_skills + 1))
  echo "cloud-package: installed skill ${name} → ${dest}"
done

if [[ "$installed_skills" -eq 0 ]]; then
  echo "cloud-package: ERROR — no skills installed from $root" >&2
  exit 1
fi

# Copy skips laptop-only names without deleting a previous dest copy, and never
# sees retired names that left the source tree. Drop dest skill dirs that are
# no longer shipped (missing source SKILL.md, or now laptop-only). Leave dest
# dirs that are not skills (no SKILL.md) alone. Directory symlinks are unlinked
# only — never `rm -rf symlink/`, which follows the referent.
# SKILLS_HOME is this installer's reconstitution dest on Cloud Agent VMs.
pruned_skills=0
shopt -s nullglob
for dest_path in "$SKILLS_HOME"/*; do
  dest_dir="${dest_path%/}"
  [[ -e "$dest_dir" || -L "$dest_dir" ]] || continue
  name="$(basename "$dest_dir")"
  if [[ -L "$dest_dir" ]]; then
    if should_ship_skill "$name"; then
      continue
    fi
    rm -f -- "$dest_dir"
    pruned_skills=$((pruned_skills + 1))
    echo "cloud-package: pruned retired skill ${name}"
    continue
  fi
  if [[ ! -d "$dest_dir" || ! -f "$dest_dir/SKILL.md" ]]; then
    continue
  fi
  if should_ship_skill "$name"; then
    continue
  fi
  rm -rf -- "$dest_dir"
  pruned_skills=$((pruned_skills + 1))
  echo "cloud-package: pruned retired skill ${name}"
done
shopt -u nullglob

# Plain *.md basename an installer could have written (no path escape, no dotfile).
is_installable_md_name() {
  [[ "$1" == *.md && "$1" != */* && "$1" != .* ]]
}

# Copy every source <kind> *.md into its dest, then prune only files an installer put there.
# Installed names are recorded in <dest>/.dotagents-installed (a dotfile, so the *.md copy never
# ships it and the name filter never prunes it); a name from the previous manifest that left the
# source is removed. Installers older than the manifest left no record, so a retired-name dest file
# is also removed when its bytes hash to a blob that path held in dotagents history
# (<src>/.retired-md-blobs): a verbatim installer copy. A user-edited retired-name file, a
# user-authored agent, another tool's rule, and non-Markdown notes never match and are never
# touched; a kept retired-name file is warned about on every run. An empty source dir fails closed.
sync_md_dir() {
  local src_dir="$1" dest_dir="$2" kind="$3"
  local manifest="${dest_dir}/${INSTALL_MANIFEST_NAME}"
  local file name blob hash installed=0 pruned=0
  local -a names=()
  mkdir -p "$dest_dir"
  shopt -s nullglob
  for file in "$src_dir"/*.md; do
    name="$(basename "$file")"
    cp -f "$file" "$dest_dir/$name"
    names+=("$name")
    installed=$((installed + 1))
    echo "cloud-package: installed ${kind} ${name} → ${dest_dir}/${name}"
  done
  shopt -u nullglob
  if [[ "$installed" -eq 0 ]]; then
    echo "cloud-package: ERROR — ${kind}s dir present but empty at $src_dir" >&2
    exit 1
  fi
  if [[ -f "$manifest" ]]; then
    while IFS= read -r name || [[ -n "$name" ]]; do
      is_installable_md_name "$name" || continue
      [[ -e "$src_dir/$name" ]] && continue
      [[ -e "$dest_dir/$name" || -L "$dest_dir/$name" ]] || continue
      rm -f -- "${dest_dir:?}/$name"
      pruned=$((pruned + 1))
      echo "cloud-package: pruned retired ${kind} ${name}"
    done <"$manifest"
  fi
  local blobs="$src_dir/$RETIRED_BLOBS_NAME" dest_abs
  dest_abs="$(cd "$dest_dir" && pwd)"
  if [[ ! -f "$blobs" ]]; then
    # A source older than the blob lists: cleanup only, so skip it rather than fail the install.
    echo "cloud-package: WARN — no ${blobs}; pre-manifest ${kind} copies not pruned" >&2
    blobs=/dev/null
  fi
  while read -r blob name || [[ -n "$blob" ]]; do
    [[ -n "$blob" && "$blob" != \#* ]] || continue
    is_installable_md_name "$name" || continue
    [[ -e "$src_dir/$name" ]] && continue
    # Regular files only: a symlink points at content the installer never wrote.
    [[ -f "$dest_dir/$name" && ! -L "$dest_dir/$name" ]] || continue
    if ! command -v git >/dev/null 2>&1; then
      echo "cloud-package: WARN — git missing; cannot hash ${dest_dir}/${name}, left in place" >&2
      continue
    fi
    # Hash from / so the caller's cwd (a SHA-256 or safe.directory-rejected repo) cannot change or
    # break the result; a failed hash keeps the file and says so rather than reading as a mismatch.
    if ! hash="$(cd / && git hash-object --no-filters -- "$dest_abs/$name")"; then
      echo "cloud-package: WARN — cannot hash ${dest_dir}/${name}, left in place" >&2
      continue
    fi
    [[ "$hash" == "$blob" ]] || continue
    rm -f -- "${dest_dir:?}/$name"
    pruned=$((pruned + 1))
    echo "cloud-package: pruned retired ${kind} ${name} (identical to a historical dotagents copy)"
  done <"$blobs"
  # A retired-name file that survived (user-edited, a symlink, or unhashable) is still loadable, so
  # say so on every run rather than leave it silent. One line per name, however many blobs it has.
  local warned=$'\n'
  while read -r blob name || [[ -n "$blob" ]]; do
    [[ -n "$blob" && "$blob" != \#* ]] || continue
    is_installable_md_name "$name" || continue
    [[ -e "$src_dir/$name" ]] && continue
    [[ -e "$dest_dir/$name" || -L "$dest_dir/$name" ]] || continue
    [[ "$warned" == *$'\n'"$name"$'\n'* ]] && continue
    warned+="$name"$'\n'
    echo "cloud-package: WARN — kept retired ${kind} ${name}: not pruned (edited, symlink, or unhashable); still loadable, remove ${dest_dir}/${name} by hand if unwanted" >&2
  done <"$blobs"
  printf '%s\n' "${names[@]}" >"${manifest}.tmp"
  mv -f "${manifest}.tmp" "$manifest"
  echo "cloud-package: ${kind}s: ${installed} installed, ${pruned} retired pruned"
}

sync_md_dir "$root/agents" "$AGENTS_HOME" agent
sync_md_dir "$root/rules" "$RULES_HOME" rule

# --- connector/plugin catalog ---
# The cloud-first canon for MCP servers and marketplace plugins (presence checked above).
mkdir -p "$MCPS_HOME"
cp -f "$root/mcps/catalog.json" "$MCPS_HOME/catalog.json"
echo "cloud-package: installed connector catalog → ${MCPS_HOME}/catalog.json"
if [[ -f "$root/mcps/README.md" ]]; then
  cp -f "$root/mcps/README.md" "$MCPS_HOME/README.md"
else
  # Installer-owned: never leave a previous revision's policy doc beside the new canon.
  rm -f "$MCPS_HOME/README.md"
fi

# --- shared pre-commit gate lib ---
# Presence checked above. Child repos must not vendor a local copy of gate-lib.sh.
install_gate_lib "$root"

echo "cloud-package: done (${installed_skills} skill(s), ${skipped_excluded} laptop-only skipped, ${pruned_skills} retired skill(s) pruned, agents + rules + catalog + gate lib installed)"
