# Generated by Django 4.2.2 on 2023-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_remove_comment_body_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
