# Generated by Django 4.2.5 on 2023-11-08 16:00

import blog.utils
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0041_disallow_null_values_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, validators=[blog.utils.snippet_validator]
            ),
        ),
    ]
