# Generated by Django 4.2.5 on 2023-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0043_update_simularities_on_existing_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
