# Generated by Django 4.2.5 on 2023-11-13 13:36

import blog.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0043_update_simularities_on_existing_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, validators=[blog.validators.snippet_validator]
            ),
        ),
    ]
