# Generated by Django 4.2.5 on 2023-12-15 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0044_post_upvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upvoters",
            field=models.ManyToManyField(
                related_name="upvoted_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
