# Generated by Django 3.2.7 on 2022-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_add_metaimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="Hello World", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
