# Generated by Django 4.1 on 2022-08-13 06:23

from django.db import migrations
import django_resized.forms
import blog.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_add_metaimg_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="metaimg",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=blog.models.get_default_metaimg,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="post_metaimgs/",
            ),
        ),
    ]
