repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: "v0.0.246"
      hooks:
          - id: ruff
            args: ["--config", "config/pyproject.toml"]
