# Generated by Django 4.0.5 on 2022-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_addr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
