# Generated by Django 4.0.5 on 2022-06-23 12:43
from django.db import migrations
from siteanalytics.utils import get_IP_details
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        import os
        print(f"The current working directory is {os.getcwd()}")
        Visitor = apps.get_model('siteanalytics', 'Visitor')
        with open("siteanalytics/data/ip_info.csv") as datafile:
            for line in datafile.readlines():
                details = get_IP_details("a", "b")
                location = Point(details.longitude, details.latitude, srid=4326)
                Visitor(
                    ip_addr=details.ip,
                    country=details.country,
                    city=details.city,
                    location=location,
                ).save()
    dependencies = [
        ("siteanalytics", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
