# Generated by Django 4.0.5 on 2022-06-23 12:43
from django.db import migrations
from siteanalytics.utils import load_data


class Migration(migrations.Migration):
    dependencies = [
        ("siteanalytics", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
