# Generated by Django 4.0.5 on 2022-06-23 12:43
from django.db import migrations
from siteanalytics.utils import get_IP_details
from django.contrib.gis.geos import fromstr
import csv
import os


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        Visitor = apps.get_model("siteanalytics", "Visitor")
        with open("siteanalytics/data/ip_info.csv") as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                try:
                    details = get_IP_details(row["ip"], os.environ["IP_INFO_TOKEN"])
                except Exception as e:
                    print(f"I had trouble parsing row {row['id']}")
                    print(e)
                location = fromstr(f'POINT({details.longitude} {details.latitude})', srid=4326)
                Visitor(
                    ip_addr=details.ip,
                    country=details.country,
                    city=details.city,
                    location=location,
                ).save()

    dependencies = [
        ("siteanalytics", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
