# Generated by Django 4.0.5 on 2022-06-28 03:11
from django.db import migrations
from django.contrib.gis.geos import fromstr
import csv
import os
import ipinfo


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        Visitor = apps.get_model("siteanalytics", "Visitor")
        print(os.getcwd())
        with open("siteanalytics/data/ip_info.csv") as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                try:
                    Visitor.objects.get(ip_addr=row["ip"])
                    continue  # If it exists, go to the next one
                except Visitor.DoesNotExist:
                    pass
                handler = ipinfo.getHandler(os.environ["IP_INFO_TOKEN"])
                details = handler.getDetails(row["ip"])
                try:
                    location = fromstr(
                        f"POINT({details.longitude} {details.latitude})", srid=4326
                    )
                except Exception as e:
                    print(f"I had trouble parsing row {row['id']}")
                    print(e)
                    continue

                Visitor(
                    ip_addr=details.ip,
                    country=details.country,
                    city=details.city,
                    location=location,
                ).save()

    dependencies = [
        ("siteanalytics", "0002_add_visitor_model"),
    ]

    operations = [migrations.RunPython(load_data)]
