#!/usr/bin/env bash

PARAMS=('-m 6 -q 70 -mt -af -progress')

if [ $# -ne 0 ]; then
	PARAMS=$@;
fi

shopt -s nullglob nocaseglob extglob globstar

for file in $PWD/**/*.@(jpg|jpeg|tif|tiff|png); do
    cwebp $PARAMS "$file" -o "${file%.*}".webp;
done
