# Generated by Django 3.2.7 on 2021-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="post_views", to="blog.IpPerson"
            ),
        ),
    ]
