# Generated by Django 3.2.7 on 2022-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_change_content_field_to_richtextuploading'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
