# Generated by Django 3.2.7 on 2022-03-07 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_snippet_to_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
