# Generated by Django 3.2.13 on 2022-05-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_add_desc_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='IpPerson',
        ),
    ]
