# Generated by Django 3.2.13 on 2022-05-27 15:06

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_removed_likes_posts_ipperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300, null=True),
        ),
    ]
