# Generated by Django 3.2.13 on 2022-06-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_transfer_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="category_link",
            new_name="category",
        ),
    ]
