# Generated by Django 3.2.13 on 2022-06-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_remove_category_rename_category_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="metaimg_alt_txt",
            field=models.CharField(default="Meta Image", max_length=120),
        ),
    ]
