# Generated by Django 4.0.6 on 2022-07-21 16:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_increase_post_title_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=110),
        ),
    ]
