# Generated by Django 4.0.6 on 2022-07-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_length_limit_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metaimg_alt_txt',
            field=models.CharField(default='John Solly Headshot', max_length=120),
        ),
    ]
