# Generated by Django 4.0.6 on 2022-07-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_change_default_text_meta_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="metaimg_mimetype",
        ),
    ]
