# Generated by Django 4.0.6 on 2022-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_mime_type_from_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metaimg_attribution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
