# Generated by Django 4.1.2 on 2023-01-28 19:01

from django.db import migrations
from django.utils.text import slugify

def create_slugs(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_add_slug_field_to_category"),
    ]

    operations = [
        migrations.RunPython(create_slugs),
    ]
