# Generated by Django 4.1.2 on 2023-01-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_slugify_category_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
