# Generated by Django 4.1.6 on 2023-06-07 20:18

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="body",
        ),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
